name: Ecommerce ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/887456464145/locations/global/workloadIdentityPools/ecommercepool/providers/github-provider'
          service_account: 'ecommerce-service-account@project-b1401e3c-6c22-44e2-ba6.iam.gserviceaccount.com'

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ecommerce-cluster
          location: asia-south1
          project_id: project-b1401e3c-6c22-44e2-ba6
          use_dns_endpoint: true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet  

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
         
      - name: Build and test with Maven
        run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build customer Docker image
        run: docker build -t customer:latest ./customer

      - name: Build product Docker image
        run: docker build -t product:latest ./product

      - name: Build order Docker image
        run: docker build -t order:latest ./order

      - name: Build notification Docker image
        run: docker build -t notification:latest ./notification

      - name: Build payment Docker image
        run: docker build -t payment:latest ./payment

      - name: Build eureka-server Docker image
        run: docker build -t eureka-server:latest ./eureka-server

      - name: Build gateway Docker image
        run: docker build -t gateway:latest ./gateway

      - name: Tag and push Docker images
        run: |
          for service in customer product order notification payment eureka-server gateway
          do
            docker tag $service:latest asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ecommerce-repo/$service:latest
            docker push asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ecommerce-repo/$service:latest
          done

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s-gke/namespace.yaml
          kubectl apply -f k8s-gke/eureka-deployment.yaml
          kubectl apply -f k8s-gke/eureka-service.yaml
          kubectl apply -f k8s-gke/customer-deployment.yaml
          kubectl apply -f k8s-gke/customer-service.yaml
          kubectl apply -f k8s-gke/product-deployment.yaml
          kubectl apply -f k8s-gke/product-service.yaml
          kubectl apply -f k8s-gke/order-deployment.yaml
          kubectl apply -f k8s-gke/order-service.yaml


      - name: CI completed
        run: echo "CI pipeline completed successfully"


      
