name: Ecommerce ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
         
      - name: Build and test with Maven
        run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      - name: CI completed
        run: echo "CI pipeline completed successfully"


      
